name: Poll RetroAchievements

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT auth
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}  # ✅ inject the PAT here directly

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Poll RA and post to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python scripts/python/check_achievements.py

      - name: Commit and push updated state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/last_polled.json
          git commit -m "chore: update last_polled [skip ci]" || echo "No changes"
          git push
